### ISSUE TITLE
Cannot manage contact log comments in Chrome / Safari

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/pyramus#283]
Contact log comment editor is in readonly mode when using Chorme

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1631

#### SH
Petra Roininen

**Comment by anttiviljakainen** [comment]
The problem seems to be that Chrome initializes hidden elements in readonly mode. We can try to go around it by initializing the comment ckeditor when it's shown but it lead to another error message from inside of ckeditor even though it seemed to work. I would maybe put this together with the ckeditor update #253.

**Comment by anttiviljakainen** [comment]
Might be issue also on safari.
